export const VALIDATE_EMAIL_FORM = 'VALIDATE_EMAIL_FORM';
export const TOGGLE_DATEPICKER_VISIBILITY = 'TOGGLE_DATEPICKER_VISIBILITY';
export const EMAIL_SENT_TOGGLE = 'EMAIL_SENT_TOGGLE';
export const SENDING_EMAIL = 'SENDING_EMAIL';
