export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const TABLELIST_REQUEST = 'TABLELIST_REQUEST';
export const TABLELIST_SUCCESS = 'TABLELIST_SUCCESS';
export const TABLELIST_ERROR = 'TABLELIST_ERROR';
